spring:
  application:
    name: SpringSecurity

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/spring-security
    password: ${DB_PASSWORD}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver

  security:
    remember-me:
      secret-key: ${REMEMBER_ME_KEY}